all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    homelab:
      PATCHING_REBOOT_TIMEOUT: 600
      PATCHING_POST_REBOOT_DELAY: 300
      PATCHING_PRE_REBOOT_DELAY: 300
      PATCHING_REBOOT_ENABLED: true

      pip_install_packages:
        - name: docker
        - name: "urllib3<2"

      docker_daemon_options:
        data-root: "/storage/2tb1/docker"
        log-opts:
          max-size: "10m"

      ansible_host: 172.25.0.200
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_pass: "invalid"

      SERVER_DRIVES:
        - device: /dev/sda1
          name: "4tb1"
          fstype: xfs
          opts: defaults
          state: mounted
          destination: /storage/4tb1
        - device: /dev/sdb1
          name: "4tb2"
          fstype: xfs
          opts: defaults
          state: mounted
          destination: /storage/4tb2
        - device: /dev/sdc1
          name: "8tb1"
          fstype: xfs
          opts: defaults
          state: mounted
          destination: /storage/8tb1
        - device: /dev/sdd1
          name: "8tb2"
          fstype: xfs
          opts: defaults
          state: mounted
          destination: /storage/8tb2
        - device: /dev/sdf1
          name: "1tb1"
          fstype: xfs
          opts: defaults
          state: mounted
          destination: /storage/1tb1
        - device: /dev/nvme0n1p1
          name: "2tb1"
          fstype: xfs
          opts: defaults
          state: mounted
          destination: /storage/2tb1
      
      TRAEFIK_PROXY_NETWORK: "traefik"
      TRAEFIK_PROXY_ID: "traefik"
      TRAEFIK_PROXY_HOST: "proxy.a.borgardt.me"
      TRAEFIK_LETSENCRYPT_EMAIL: "alexander.borgardt@gmail.com"
      TRAEFIK_LETSENCRYPT_VOLUME: "traefik_letsencrypt"
      TRAEFIK_HTPASSWD_USER: "admin"
      TRAEFIK_HTPASSWD_HASH: "$apr1$nztls6rq$DHOe9kqVXJPC7vNOFRQT2/"
      TRAEFIK_IONOS_API_KEY : "2ac03799f8354878aa6b560ec03b3ca5.M-LF905rsPPFkymkBYQKQYakEjh3pPtDPw84XRliB7fo_2h6dbVBjcMlaH60-HM2eCf-lLy_AHlW-PuwtZmwOA"
      TRAEFIK_ENVIRONMENT:
        IONOS_API_KEY: "{{ TRAEFIK_IONOS_API_KEY }}"
      TRAEFIK_STATIC_ROUTES:
        - rule: "Host(`dns.a.borgardt.me`)"
          name: "pihole"
          url: "http://172.25.0.200:81/admin/"
          use_service_certs: false
        - rule: "Host(`stream.a.borgardt.me`)"
          name: "jellyfin"
          url: "http://172.25.0.200:8096/"
          use_service_certs: false
        - rule: "Host(`ha.borgardt.me`)"
          name: "homeassistant"
          url: "http://172.25.0.245:8123"
          use_service_certs: false
        - rule: "Host(`dashdot.a.borgardt.me`)"
          name: "dashdot"
          url: "http://172.25.0.200:3001"
          use_service_certs: false
        - rule: "Host(`wazuh.a.borgardt.me`)"
          name: "wazuh"
          url: "https://172.25.0.200:5601"
          use_service_certs: true

      TRAEFIK_COMMAND:
        - --log.level=WARN
        - --api.insecure=false
        - --api.dashboard=true
        - --providers.file.directory=/etc/traefik
        - --providers.file.watch=true
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false
        - --entrypoints.web=true
        - --entrypoints.web.address=:80
        - --entrypoints.websecure=true
        - --entrypoints.websecure.address=:443
        - --certificatesresolvers.letsencrypt.acme.email={{ TRAEFIK_LETSENCRYPT_EMAIL }}
        - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
        - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=ionos
        - --certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=0

      PORTAINER_PROXY_HOST: portainer.a.borgardt.me

      AUTHELIA_PROXY_ID: "authelia"

      PRISM_PROXY_HOST: images.a.borgardt.me
      PRISM_ENVIRONMENT:
        PHOTOPRISM_SITE_URL: "https://{{ PRISM_PROXY_HOST }}"
        PHOTOPRISM_AUTH_MODE: "public"
        PHOTOPRISM_UPLOAD_NSFW: "true"
        PHOTOPRISM_DATABASE_DRIVER: "mysql"
        PHOTOPRISM_DATABASE_SERVER: "prism-db:3306"
        PHOTOPRISM_DATABASE_NAME: "photoprism"
        PHOTOPRISM_DATABASE_USER: "photoprism"
        PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
        PHOTOPRISM_EXPERIMENTAL: "true"
        PHOTOPRISM_DEFAULT_LOCALE: "de"
        PHOTOPRISM_FACE_SIZE: "20"

      PRISM_DATABASE_ENV:
        MARIADB_AUTO_UPGRADE: "1"
        MARIADB_INITDB_SKIP_TZINFO: "1"
        MARIADB_DATABASE: "photoprism"
        MARIADB_USER: "photoprism"
        MARIADB_PASSWORD: "photoprism"
        MARIADB_RANDOM_ROOT_PASSWORD: "yes"

      PIHOLE_PROXY_HOST: dns.a.borgardt.me
      PIHOLE_ENVIRONMENT:
        TZ: 'Europe/Berlin'
        WEBPASSWORD: 'invalid'
      
      JELLYFIN_ENVIRONMENT:
        JELLYFIN_PublishedServerUrl: "https://stream.a.borgardt.me"
      
      PAPERLESS_PROXY_HOST: docs.a.borgardt.me
      
      HOMARR_PROXY_HOST: startpage.a.borgardt.me
