---
PAPERLESS_PROXY_ID: paperlessngx
PAPERLESS_PROXY_NETWORK: traefik
PAPERLESS_PROXY_HOST: docs.localhost
PAPERLESS_USE_TRAEFIK: true
PAPERLESS_DBPASS: paperless
PAPERLESS_ROOT_DBPASS: paperless
PAPERLESS_SECRET_KEY: "insecure"
PAPERLESS_ADMIN_PASSWORD: "insecure"

PAPERLESS_ENV:
  PAPERLESS_OCR_LANGUAGES: "deu eng"
  PAPERLESS_URL: "https://{{ PAPERLESS_PROXY_HOST }}"
  PAPERLESS_SECRET_KEY: "{{ PAPERLESS_SECRET_KEY }}"
  PAPERLESS_TIME_ZONE: "Europe/Berlin"
  PAPERLESS_ADMIN_USER: admin
  PAPERLESS_ADMIN_PASSWORD: "{{ PAPERLESS_ADMIN_PASSWORD }}"
  PAPERLESS_REDIS: "redis://paperless-redis:6379"
  PAPERLESS_DBENGINE: "mariadb"
  PAPERLESS_DBHOST: "paperless-database"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_DBPASS: "{{ PAPERLESS_DBPASS }}"
  PAPERLESS_DBPORT: "3306"
  PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'

PAPERLESS_DATABASE_ENV:
  MARIADB_AUTO_UPGRADE: "1"
  MARIADB_INITDB_SKIP_TZINFO: "1"
  MARIADB_DATABASE: paperless
  MARIADB_USER: paperless
  MARIADB_PASSWORD: "{{ PAPERLESS_DBPASS }}"
  MARIADB_ROOT_PASSWORD: "{{ PAPERLESS_ROOT_DBPASS }}"